### ISSUE TITLE
ClassCastException / unison: Short read, expected 8 bytes

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#310]
My test code

```
type Json.Value = Object [Pair Text Json.Value]
                | Array [Json.Value]
                | String Text
                | Number Float
                | Bool Boolean
                | Null

format : Json.Value -> Text
format v = case v of
  Json.Value.String s -> "'" ++ s ++ "'"
  Json.Value.Bool True -> "true"
  Json.Value.Bool False -> "false"
  _ -> "TODO"

> a = Json.Value.Array [Json.Value.String "foo"]
> format a
```

result

```
master>

  ┌
  │  ✅
  │
  │  I found and typechecked these definitions in /Users/francisdb/workspace/unison/unison-src/json.u:
  │
  │    type Json.Value
  │
  │  Now evaluating any watch expressions (lines starting with `>`) ...
  └

java.lang.ClassCastException: org.unisonweb.Builtins$External$$anon$7 cannot be cast to org.unisonweb.Value$Data
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compilePattern$7(compilation.scala:373)
	at org.unisonweb.compilation.package$$anonfun$compilePattern$17.apply(compilation.scala:371)
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compileMatchCase$3(compilation.scala:331)
	at org.unisonweb.compilation.package$$anonfun$compileMatchCase$6.apply(compilation.scala:324)
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$10(compilation.scala:1059)
	at org.unisonweb.compilation.package$$anonfun$sequenceCases$1$1.apply(compilation.scala:1058)
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$12(compilation.scala:1070)
	at org.unisonweb.compilation.package$$anonfun$compile$28.apply(compilation.scala:1066)
	at org.unisonweb.Value$Lambda.apply(Param.scala:79)
	at org.unisonweb.compilation.package$.invokeDynamic$1(compilation.scala:658)
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$dynamicCall$1(compilation.scala:750)
	at org.unisonweb.compilation.package$$anonfun$dynamicCall$2.apply(compilation.scala:714)
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$13(compilation.scala:1452)
	at org.unisonweb.compilation.package$$anonfun$compile$29.apply(compilation.scala:1087)
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$13(compilation.scala:1102)
	at org.unisonweb.compilation.package$$anonfun$compile$29.apply(compilation.scala:1087)
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$13(compilation.scala:1102)
	at org.unisonweb.compilation.package$$anonfun$compile$29.apply(compilation.scala:1087)
	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$13(compilation.scala:1102)
	at org.unisonweb.compilation.package$$anonfun$compile$29.apply(compilation.scala:1087)
	at org.unisonweb.compilation.package$.run(compilation.scala:1452)
	at org.unisonweb.Bootstrap0$.$anonfun$normalizedFromBinarySource$1(Bootstrap.scala:132)
	at org.unisonweb.BootstrapStream$.$anonfun$main$5(Bootstrap.scala:169)
	at org.unisonweb.BootstrapStream$.$anonfun$main$5$adapted(Bootstrap.scala:71)
	at org.unisonweb.BootstrapStream$.main(Bootstrap.scala:71)
	at org.unisonweb.BootstrapStream.main(Bootstrap.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:106)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:132)
	at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:106)
	at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:98)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:132)
	at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:28)
	at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:27)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
	at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:35)
	at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:34)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:73)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:92)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
unison: Short read, expected 8 bytes
Well that didn't work.
Press any key to re-launch.

```

**Comment by francisdb** [comment]
Also strange it does not fail earlier on this `True` instead of `true`

**Comment by aryairani** [comment]
It doesn't fail on `True` because it just binds `True` as a wildcard variable; there's nothing special about upper-case ids here like there is in Haskell.

Non-crashing as of aa6f3ec7f1abd4f593024e6ee13436b21a477504.
```
  ┌
  │  16 | > format a
  │         ⧩
  │         "TODO"
  └
  ┌
  │  15 | > a = Json.Value.Array [Json.Value.String "foo"]
  │         ⧩
  │         Json.Value.Array [Json.Value.String "foo"]
  └

```

**Comment by aryairani** [comment]
Not exactly sure why it doesn't hang up on `True`; I'm guessing that only the first identifier (`Json.Value.Bool`) is parsed as a constructor, and the rest are all treated as variables.
