### ISSUE TITLE
recursive nested pattern match returns wrong type

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#346]
I have the code below

```haskell
type Either a b = Left a | Right b

lexString : Text -> Either Text (Text, Text)
lexString t =
  go : Text -> Text -> Either Text (Text, Text)
  go acc rest =
    c = Text.take 1 rest
    case c of
      b | b == "\"" -> Either.Right ( acc, Text.drop 1 rest)
      c             -> go (acc ++ c) (Text.drop 1 rest)
  go "" (Text.drop 1 t)

lex : Text -> [Text]
lex t =
  case lexString t of
    Either.Right (str, rest) -> [str]
    Either.Left err -> [err]

```

strangely the lex function returns a `[(Text,Text)]` instead of `[Text]`

```

  ┌
  │  ✅
  │
  │  I found and typechecked these definitions in /Users/francisdb/workspace/unison-json/src/test.u:
  │
  │    type Either a b
  │    lex : Text -> [Text]
  │    lexString : Text -> Either Text (Text, Text)
  │
  │  Now evaluating any watch expressions (lines starting with `>`) ...
  └

  ┌
  │  21 | > lex "\"foo\""
  │         ⧩
  │         Con #5cbWz9X1yckJnAbgh5HMxCAWwB9otVmzy6km1BE5gQ1KscRk9ZZZrD55tSXZzm2qWreQV6FsX5DkpmyCiAFei3La 1
  │           ("foo", "")
```

And continuing with that value of course causes havoc

```
> Sequence.at 0 ( lex "\"foo\"")
```

```
master>

  ┌
  │  ✅
  │
  │  I found and typechecked these definitions in /Users/francisdb/workspace/unison-json/src/test.u:
  │
  │    type Either a b
  │    lex : Text -> [Text]
  │    lexString : Text -> Either Text (Text, Text)
  │
  │  Now evaluating any watch expressions (lines starting with `>`) ...
  └
[error] (run-main-0) java.lang.ClassCastException: org.unisonweb.Value$Data cannot be cast to org.unisonweb.Builtins$External
[error] java.lang.ClassCastException: org.unisonweb.Value$Data cannot be cast to org.unisonweb.Builtins$External
[error] 	at org.unisonweb.Builtins$LowPriorityDecode.$anonfun$decodeAssumeExternal$1(Builtins.scala:897)
[error] 	at org.unisonweb.Builtins$.org$unisonweb$Builtins$$$anonfun$_fup_p$1(Builtins.scala:728)
[error] 	at org.unisonweb.Builtins$$anonfun$6.apply(Builtins.scala:727)
[error] 	at org.unisonweb.compilation.package$Computation$C2P.apply(compilation.scala:161)
[error] 	at org.unisonweb.Value$Lambda.apply(Param.scala:79)
[error] 	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compileStaticFullySaturatedNontailCall$2(compilation.scala:446)
[error] 	at org.unisonweb.compilation.package$$anonfun$compileStaticFullySaturatedNontailCall$5.apply(compilation.scala:441)
[error] 	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$13(compilation.scala:1102)
[error] 	at org.unisonweb.compilation.package$$anonfun$compile$29.apply(compilation.scala:1087)
[error] 	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$13(compilation.scala:1452)
[error] 	at org.unisonweb.compilation.package$$anonfun$compile$29.apply(compilation.scala:1087)
[error] 	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$13(compilation.scala:1102)
[error] 	at org.unisonweb.compilation.package$$anonfun$compile$29.apply(compilation.scala:1087)
[error] 	at org.unisonweb.compilation.package$.org$unisonweb$compilation$package$$$anonfun$compile$13(compilation.scala:1102)
[error] 	at org.unisonweb.compilation.package$$anonfun$compile$29.apply(compilation.scala:1087)
[error] 	at org.unisonweb.compilation.package$.run(compilation.scala:1452)
[error] 	at org.unisonweb.Bootstrap0$.$anonfun$normalizedFromBinarySource$1(Bootstrap.scala:132)
[error] 	at org.unisonweb.BootstrapStream$.$anonfun$main$5(Bootstrap.scala:169)
[error] 	at org.unisonweb.BootstrapStream$.$anonfun$main$5$adapted(Bootstrap.scala:71)
[error] 	at org.unisonweb.BootstrapStream$.main(Bootstrap.scala:71)
[error] 	at org.unisonweb.BootstrapStream.main(Bootstrap.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (main / Compile / runMain) Nonzero exit code: 1
[error] Total time: 56 s, completed Feb 18, 2019 11:32:50 AM
unison: Short read, expected 8 bytes
```

**Comment by francisdb** [comment]
I have the same problem with the Haskell runtime where the returned variables are mixed up

```
lexNumber : Text -> Either Text (Text, Text)
lexNumber t =
  go : Text -> Text -> Either Text (Text, Text)
  go acc rest =
    c = Text.take 1 rest
    case Text.size c of
      0 -> Either.Right ( acc, rest)
      1 ->
        case c of
          n | isNumeric n  -> go (acc ++ n) (Text.drop 1 rest)
          _                -> Either.Right ( acc, rest)
  go "" t
```

```
┌
  │  176 | > lexNumber "3.14,true]}"
  │          ⧩
  │          Con #"5cbW 1 (",true]}", ",")
  └
```

**Comment by francisdb** [comment]
closing as this is fixed in the rt1 haskell runtime branch
